apiVersion: batch/v1
kind: CronJob
metadata:
  name: price-updater
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: price-updater
          restartPolicy: Never
          priorityClassName: null
          containers:
          - name: price-updater
            image: curlimages/curl:8.10.1
            command: ["/bin/sh","-c"]
            args:
            - |
              for i in $(seq 12); do \
                curl -fsS \
                  -H 'Content-Type: application/json' \
                  -H 'User-Agent: PriceUpdater/CronJob/1.0' \
                  -m 30 -X POST \
                  http://token-price-service:3000/pricing/trigger-update \
                  || echo "request failed"; \
                sleep 5; \
              done
