apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- configmap.yaml
- pvc-data.yaml
- pvc-logs.yaml
- service.yaml
- deployment.yaml
- ingress.yaml
- cronjob.yaml
- kafka-deployment.yaml
- kafka-service.yaml
- zookeeper-deployment.yaml
- zookeeper-service.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- postgres-pvc.yaml