apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: token-price-service
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          # Для тестовой среды без PV; для персистентности добавь PVC на /var/lib/zookeeper/log и /var/lib/zookeeper/data
          readinessProbe:
            tcpSocket: { port: 2181 }
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            tcpSocket: { port: 2181 }
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6