apiVersion: batch/v1
kind: CronJob
metadata:
  name: price-updater
spec:
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: price-updater
            resources:
              requests:
                cpu: "5m"
                memory: "16Mi"
              limits:
                cpu: "20m"
                memory: "64Mi"
