apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-price-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: token-price-service
        image: docker.io/uniwertz/token-price-service:prod-202510141657
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "20m"
            memory: "96Mi"
          limits:
            cpu: "80m"
            memory: "192Mi"
