apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-price-service
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-cred
      containers:
      - name: token-price-service
        image: ghcr.io/uniwertz/token-price-service:main-78bee2fa6aaa79408c0fece22583feefba475fc8
        imagePullPolicy: IfNotPresent