apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-price-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: token-price-service
        image: ghcr.io/uniwertz/token-price-service:latest
        imagePullPolicy: IfNotPresent