apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-price-service
  namespace: token-price-service-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: token-price-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
